<a href="https://colab.research.google.com/github/Nattakonjpg/AIPrototype2023/blob/main/AI_Prototype.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import

In [1]:
import tensorflow as tf
from tensorflow import keras #interface
from tensorflow.keras import layers

##Define


In [14]:
#Define Sequential model with 3 Layers
model = keras.Sequential(
        [
             keras.Input(shape=(4,)), #4 Node
             layers.Dense(2, activation="relu", name="layer1"), #Dense = fully connected
             layers.Dense(3, activation="relu", name="layer2"),
             layers.Dense(5, name="output")  #4 class
        ]
)

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 layer1 (Dense)              (None, 2)                 10        
                                                                 
 layer2 (Dense)              (None, 3)                 9         
                                                                 
 output (Dense)              (None, 5)                 20        
                                                                 
Total params: 39 (156.00 Byte)
Trainable params: 39 (156.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


###predict

In [19]:
x = tf.ones((5, 5)) #5 row 4 columns = else is 1, batch size = 5

In [8]:
x

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [17]:
y = model(x)

In [20]:
y

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.05855815,  0.20337819, -0.02154016,  0.06831552, -0.09714634],
       [ 0.05855815,  0.20337819, -0.02154016,  0.06831552, -0.09714634],
       [ 0.05855815,  0.20337819, -0.02154016,  0.06831552, -0.09714634],
       [ 0.05855815,  0.20337819, -0.02154016,  0.06831552, -0.09714634],
       [ 0.05855815,  0.20337819, -0.02154016,  0.06831552, -0.09714634]],
      dtype=float32)>